apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-prometheus-operator
  labels:
    expose: "{{ .Values.prometheusOperator.service.expose }}"
{{ include "labels.stakater-po" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  annotations:
    fabric8.io/ingress.annotations: |-
      ingress.kubernetes.io/force-ssl-redirect: "{{ .Values.prometheusOperator.service.forceSslRedirect }}"
      kubernetes.io/ingress.class: {{ .Values.prometheusOperator.service.ingressClass }}
      {{- with .Values.prometheusOperator.service.annotations }}
      {{- range $key, $value := . }}
      {{ $key }}: {{ $value }}
      {{- end }}
      {{- end }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    k8s-app: {{ template "name" . }}-prometheus-operator
