apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "monitoring.name" . }}-prometheus-k8s-rules
  namespace: {{ .Release.Namespace }}
  labels:
    role: prometheus-rulefiles
    prometheus: {{ .Values.prometheus.prometheusLabel }}
{{ include "monitoring.labels.stakater-prom" . | indent 4 }}
{{ include "monitoring.labels.chart" . | indent 4 }}
data:
{{ toYaml .Values.prometheus.configmap.data | indent 2}}
