apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}-prometheus-k8s-rules
  namespace: {{ .Values.prometheus.namespace }}
  labels:
    role: prometheus-rulefiles
    prometheus: {{ .Values.prometheus.prometheusLabel }}
{{ include "labels.stakater-prom" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
data:
{{ toYaml .Values.prometheus.configmap.data | indent 2}}
