apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
{{ include "monitoring.labels.stakater-prom" . | indent 4 }}
{{ include "monitoring.labels.chart" . | indent 4 }}
  name: ssd
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "{{ .Values.prometheus.storageclass.isDefaultClass }}"
    {{- with .Values.prometheus.storageclass.annotations }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value }}
    {{- end }}
    {{- end }}
provisioner: kubernetes.io/aws-ebs
parameters:
  zone: {{ .Values.global.nodeSelectorZone }}
  type: gp2